import os
import json
import urllib.parse
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional
from backend.database import get_db_connection, execute_query
from backend.armoriq.receipts import save_tool_receipt

def convert_to_google_datetime(date_str: str, duration_days: int = 1) -> str:
    """
    Converts a date string (YYYY-MM-DD) to Google Calendar URL template format.
    Ensures correct day math since Google template dates are exclusive for all-day events.
    """
    try:
        clean_date = date_str.split("T")[0]
        dt = datetime.strptime(clean_date, "%Y-%m-%d")
        start_val = dt.strftime("%Y%m%d")
        
        # End date is exclusive for Google Calendar template action
        end_dt = dt + timedelta(days=max(1, duration_days))
        end_val = end_dt.strftime("%Y%m%d")
        
        return f"{start_val}/{end_val}"
    except Exception:
        # Fallback date range
        today = datetime.utcnow()
        tomorrow = today + timedelta(days=1)
        return f"{today.strftime('%Y%m%d')}/{tomorrow.strftime('%Y%m%d')}"

def generate_event_description(project_name: str, task: dict, project_id: int) -> str:
    """
    Compiles detailed event description.
    """
    task_name = task.get("name", "Unnamed Task")
    deliverable = task.get("deliverable", "No deliverable specified")
    dependencies = task.get("dependencies", "None")
    
    # Calculate duration
    start_str = task.get("start", "")
    end_str = task.get("end", "")
    duration_days = 1
    try:
        if start_str and end_str:
            sd = datetime.strptime(start_str.split("T")[0], "%Y-%m-%d")
            ed = datetime.strptime(end_str.split("T")[0], "%Y-%m-%d")
            duration_days = (ed - sd).days
            if duration_days <= 0:
                duration_days = 1
    except Exception:
        pass

    priority = "High" if "PCB" in task_name or "Firmware" in task_name or "Design" in task_name else "Medium"

    description_lines = [
        f"Project: {project_name}",
        f"Task: {task_name}",
        f"Estimated Duration: {duration_days} Days",
        f"Priority: {priority}",
        f"Dependencies: {dependencies}",
        f"Expected Deliverables: {deliverable}",
        "",
        f"Reference URL: http://localhost:3000/project/{project_id}",
        f"BOM Summary: http://localhost:3000/project/{project_id}#bom",
        "Generated by WorkflowGuide AI"
    ]
    return "\n".join(description_lines)

def generate_google_calendar_url(project_id: int, project_name: str, task: dict, timezone: str) -> str:
    """
    Generates a Google Calendar template URL prefilled with event metadata.
    """
    task_name = task.get("name", "Engineering Task")
    
    # Title
    title = f"{project_name} - {task_name}"
    
    # Dates
    start_str = task.get("start", "")
    end_str = task.get("end", "")
    duration_days = 1
    try:
        if start_str and end_str:
            sd = datetime.strptime(start_str.split("T")[0], "%Y-%m-%d")
            ed = datetime.strptime(end_str.split("T")[0], "%Y-%m-%d")
            duration_days = (ed - sd).days
            if duration_days <= 0:
                duration_days = 1
    except Exception:
        pass
        
    dates = convert_to_google_datetime(start_str or datetime.utcnow().strftime("%Y-%m-%d"), duration_days)
    
    # Details & description
    details = generate_event_description(project_name, task, project_id)
    location = "WorkflowGuide AI"
    
    params = {
        "action": "TEMPLATE",
        "text": title,
        "dates": dates,
        "details": details,
        "location": location,
        "ctz": timezone
    }
    
    query_string = urllib.parse.urlencode(params)
    return f"https://calendar.google.com/calendar/render?{query_string}"

def generate_multiple_event_links(
    project_id: Any,
    task_ids: List[str],
    timezone: str,
    tasks: Optional[List[Dict[str, Any]]] = None,
    project_name: Optional[str] = None
) -> List[Dict[str, Any]]:
    """
    Generates Google Calendar deep links for selected tasks, logs them in Postgres/SQLite, and returns them.
    """
    gantt_tasks = []
    resolved_project_name = project_name or f"Project {project_id}"

    if tasks and isinstance(tasks, list) and len(tasks) > 0:
        gantt_tasks = tasks
    else:
        try:
            conn = get_db_connection()
            query = "SELECT name, gantt FROM projects WHERE id = ?"
            cursor = execute_query(conn, query, (project_id,))
            row = cursor.fetchone()
            conn.close()

            if row:
                resolved_project_name = row["name"] or resolved_project_name
                try:
                    gantt_tasks = json.loads(row["gantt"]) if row["gantt"] else []
                except Exception:
                    gantt_tasks = []
        except Exception:
            gantt_tasks = []

    # Filter tasks by selected IDs if task_ids provided, otherwise use all
    if task_ids and len(task_ids) > 0:
        selected_tasks = [t for t in gantt_tasks if str(t.get("id")) in task_ids or t.get("name") in task_ids]
        if not selected_tasks:
            selected_tasks = [t for t in gantt_tasks if t.get("name") in task_ids]
        if not selected_tasks:
            selected_tasks = gantt_tasks
    else:
        selected_tasks = gantt_tasks

    results = []
    generated_links = []
    exported_names = []

    for task in selected_tasks:
        url = generate_google_calendar_url(project_id, resolved_project_name, task, timezone)
        results.append({
            "task_id": task.get("id", task.get("name")),
            "task_name": task.get("name"),
            "google_calendar_link": url
        })
        generated_links.append(url)
        exported_names.append(task.get("name", "Task"))

    # Log to SQLite / Postgres (graceful fallback)
    try:
        conn = get_db_connection()
        log_query = """
            INSERT INTO calendar_exports (project_id, export_time, export_type, calendar_link, tasks_exported, status)
            VALUES (?, ?, ?, ?, ?, ?)
        """
        timestamp = datetime.utcnow().isoformat()
        first_link = generated_links[0] if generated_links else ""
        execute_query(conn, log_query, (
            str(project_id),
            timestamp,
            "Google Calendar Link",
            first_link,
            json.dumps(exported_names),
            "Success" if results else "Empty"
        ))
        conn.commit()
        conn.close()
    except Exception:
        pass

    # Generate ArmorIQ Receipt
    save_tool_receipt(
        "CalendarExportAgent",
        "Planner Agent",
        "calendar.generate_link",
        ["calendar.generate_link"],
        "SUCCESS",
        f"Generated {len(results)} Google Calendar deep links for project {project_id}"
    )

    return results
