"""
Deterministic mock reasoning provider for ComponentPlanningAgent offline testing and CLI demo mode.
"""

from typing import Optional, Type, TypeVar
from pydantic import BaseModel
from research_agents.component_planning_agent.providers.base import ReasoningProvider

T = TypeVar("T", bound=BaseModel)


class MockComponentPlanningProvider(ReasoningProvider):
    """Deterministic offline reasoning provider simulating Bedrock BOM synthesis."""

    async def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        max_tokens: Optional[int] = None,
        temperature: Optional[float] = None,
    ) -> str:
        return "BOM planning completed."

    async def generate_structured(
        self,
        prompt: str,
        schema: Type[T],
        system_prompt: Optional[str] = None,
    ) -> T:
        # Dynamically instantiate requested schema with realistic mock fields
        data = {
            "bom_id": "BOM-SAR-001",
            "project_id": "proj_sar_drone_001",
            "version": "1.0",
            "summary": {
                "total_line_items": 12,
                "selected_items": 8,
                "candidate_items": 3,
                "pending_items": 1,
                "subsystem_count": 5,
            },
            "items": [
                {
                    "bom_item_id": "BOM-001",
                    "line_number": 1,
                    "category": "SBC",
                    "part_number": "900-13766-0000-000",
                    "manufacturer": "NVIDIA",
                    "component_name": "Jetson Orin Nano 8GB Developer Kit",
                    "description": "40 TOPS AI compute module with 8GB LPDDR5 and carrier board.",
                    "quantity": 1,
                    "unit": "pcs",
                    "subsystem_id": "SUB-001",
                    "role": "primary_edge_compute",
                    "selection_status": "selected",
                    "required_specifications": {"ai_compute": ">= 40 TOPS", "memory": "8 GB LPDDR5", "voltage": "5.0 V DC"},
                    "known_specifications": {"ai_compute": "40 TOPS", "memory": "8 GB LPDDR5", "operating_voltage": "5.0 V - 20.0 V"},
                    "interfaces": ["SPI", "UART", "I2C", "CSI", "USB 3.2", "Ethernet"],
                    "power_requirements": {"voltage": "5.0 V", "peak_power": "15 W", "estimated_current": "3.0 A - 4.5 A"},
                    "mechanical_requirements": {"dimensions": "100 mm x 79 mm x 29 mm", "mounting": "Fuselage central bay"},
                    "software_requirements": ["Linux JetPack 6.0", "TensorRT 8.6", "ROS 2 Humble"],
                    "dependencies": ["DEP-PWR-001", "DEP-COMM-001"],
                    "datasheet_url": "https://developer.nvidia.com/embedded/jetson-orin-nano-developer-kit",
                    "alternatives": [
                        {
                            "alternative_id": "ALT-001",
                            "part_number": "SC1111",
                            "manufacturer": "Raspberry Pi",
                            "compatibility": "architecture_alternative",
                            "differences": ["Lower AI performance (~0.5 TOPS vs 40 TOPS)", "Lower power (5W vs 15W)"],
                            "reason": "Low-cost alternative if AI inference is offloaded to ground station.",
                            "confidence": 0.85,
                        }
                    ],
                    "selection_reason": "Satisfies hard real-time 45 FPS thermal inference constraint.",
                    "confidence": 0.96,
                    "source_evidence_ids": ["ev_p_001"],
                    "validation_required": False,
                },
                {
                    "bom_item_id": "BOM-002",
                    "line_number": 2,
                    "category": "thermal camera",
                    "part_number": "500-0771-01",
                    "manufacturer": "Teledyne FLIR",
                    "component_name": "FLIR Lepton 3.5 Radiometric LWIR Core",
                    "description": "160x120 radiometric thermal camera core with shutter.",
                    "quantity": 1,
                    "unit": "pcs",
                    "subsystem_id": "SUB-002",
                    "role": "radiometric_thermal_sensor",
                    "selection_status": "selected",
                    "required_specifications": {"resolution": "160x120", "type": "LWIR radiometric", "interface": "SPI VoSPI"},
                    "known_specifications": {"resolution": "160x120", "spectral_range": "8-14 um", "operating_voltage": "2.8V - 3.1V"},
                    "interfaces": ["SPI", "I2C (CCI)"],
                    "power_requirements": {"voltage": "3.3 V Logic / 2.8 V Core", "power": "150 mW"},
                    "mechanical_requirements": {"dimensions": "11.8 mm x 12.7 mm x 7.2 mm"},
                    "software_requirements": ["VoSPI DMA driver", "libuvc"],
                    "dependencies": ["DEP-PWR-002"],
                    "datasheet_url": "https://flir.netx.net/file/asset/15291/original/attachment",
                    "alternatives": [
                        {
                            "alternative_id": "ALT-002",
                            "part_number": "MLX90640",
                            "manufacturer": "Melexis",
                            "compatibility": "partial_compatibility",
                            "differences": ["Lower resolution (32x24 vs 160x120)", "I2C only"],
                            "reason": "Budget thermal sensor for low-altitude basic presence detection.",
                            "confidence": 0.70,
                        }
                    ],
                    "selection_reason": "Meets thermal human recognition requirement at 50m standoff distance.",
                    "confidence": 0.98,
                    "source_evidence_ids": ["ev_p_001"],
                    "validation_required": False,
                },
                {
                    "bom_item_id": "BOM-003",
                    "line_number": 3,
                    "category": "microcontroller",
                    "part_number": "ESP32-S3-WROOM-1-N8R8",
                    "manufacturer": "Espressif Systems",
                    "component_name": "ESP32-S3 Dual-Core Wi-Fi/BLE Module",
                    "description": "Dual-core Xtensa LX7 MCU with 8MB Flash and 8MB Octal PSRAM.",
                    "quantity": 1,
                    "unit": "pcs",
                    "subsystem_id": "SUB-004",
                    "role": "flight_safety_controller",
                    "selection_status": "selected",
                    "required_specifications": {"architecture": "Dual-Core 240MHz", "memory": ">= 4MB Flash", "connectivity": "Wi-Fi + BLE"},
                    "known_specifications": {"flash": "8 MB", "psram": "8 MB", "gpio_count": "36", "voltage": "3.0V - 3.6V"},
                    "interfaces": ["UART", "SPI", "I2C", "PWM", "Wi-Fi", "Bluetooth LE"],
                    "power_requirements": {"voltage": "3.3 V", "current_peak": "500 mA"},
                    "mechanical_requirements": {"package": "SMD Module"},
                    "software_requirements": ["ESP-IDF v5.1", "micro-ROS"],
                    "dependencies": [],
                    "datasheet_url": "https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf",
                    "alternatives": [
                        {
                            "alternative_id": "ALT-003",
                            "part_number": "STM32F405RGT6",
                            "manufacturer": "STMicroelectronics",
                            "compatibility": "electrically_compatible",
                            "differences": ["No integrated Wi-Fi/BLE", "Higher ADC sampling rate"],
                            "reason": "Standard industrial drone autopilot MCU without integrated wireless.",
                            "confidence": 0.90,
                        }
                    ],
                    "selection_reason": "Combines micro-ROS bridge and 2.4 GHz ground telemetry into a single controller.",
                    "confidence": 0.95,
                    "source_evidence_ids": [],
                    "validation_required": False,
                },
                {
                    "bom_item_id": "BOM-004",
                    "line_number": 4,
                    "category": "DC-DC converter",
                    "part_number": "TPS565208DDCR",
                    "manufacturer": "Texas Instruments",
                    "component_name": "5V/5A Synchronous Step-Down Buck Converter",
                    "description": "4.5V to 17V input, 5A synchronous step-down voltage regulator.",
                    "quantity": 1,
                    "unit": "pcs",
                    "subsystem_id": "SUB-003",
                    "role": "compute_power_regulator",
                    "selection_status": "selected",
                    "required_specifications": {"input_voltage": "14.8 V Nominal", "output_voltage": "5.0 V", "output_current": ">= 4.5 A"},
                    "known_specifications": {"input_voltage": "4.5V - 17.0V", "output_voltage": "0.6V - 7.0V adjustable", "current_max": "5.0 A"},
                    "interfaces": ["Power In", "Power Out"],
                    "power_requirements": {"efficiency": "92%"},
                    "mechanical_requirements": {"package": "SOT-23-6"},
                    "software_requirements": [],
                    "dependencies": ["DEP-PASSIVE-001"],
                    "datasheet_url": "https://www.ti.com/lit/ds/symlink/tps565208.pdf",
                    "alternatives": [],
                    "selection_reason": "High-efficiency step-down conversion from 4S LiPo to Jetson 5V rail.",
                    "confidence": 0.94,
                    "source_evidence_ids": [],
                    "validation_required": True,
                },
                {
                    "bom_item_id": "BOM-005",
                    "line_number": 5,
                    "category": "capacitor",
                    "part_number": "ECAS0D107M010K00",
                    "manufacturer": "Murata",
                    "component_name": "1000uF 6.3V Solid Polymer Decoupling Capacitor",
                    "description": "Low-ESR (10 mOhm) solid polymer aluminum electrolytic capacitor.",
                    "quantity": 1,
                    "unit": "pcs",
                    "subsystem_id": "SUB-003",
                    "role": "gpu_transient_bulk_decoupling",
                    "selection_status": "selected",
                    "required_specifications": {"capacitance": "1000 uF", "voltage_rating": ">= 6.3 V", "esr": "<= 15 mOhm"},
                    "known_specifications": {"capacitance": "1000 uF", "voltage_rating": "6.3 V", "esr": "10 mOhm"},
                    "interfaces": [],
                    "power_requirements": {},
                    "mechanical_requirements": {"package": "SMD Radial"},
                    "software_requirements": [],
                    "dependencies": [],
                    "datasheet_url": "https://www.murata.com/en-global/products/productdetail?partno=ECAS0D107M010K00",
                    "alternatives": [],
                    "selection_reason": "Suppresses GPU burst voltage droop on the 5V power bus.",
                    "confidence": 0.95,
                    "source_evidence_ids": [],
                    "validation_required": False,
                },
                {
                    "bom_item_id": "BOM-006",
                    "line_number": 6,
                    "category": "battery",
                    "part_number": "component_selection_pending",
                    "manufacturer": "Generic / Pending",
                    "component_name": "4S 14.8V 5000mAh 45C LiPo Battery Pack",
                    "description": "High-discharge 4S lithium polymer battery pack with XT60 connector.",
                    "quantity": 1,
                    "unit": "pcs",
                    "subsystem_id": "SUB-003",
                    "role": "main_energy_storage",
                    "selection_status": "pending",
                    "required_specifications": {"voltage_nominal": "14.8 V", "capacity": ">= 5000 mAh", "discharge_rate": ">= 30 C"},
                    "known_specifications": {},
                    "interfaces": ["XT60 High Current", "JST-XH Balance"],
                    "power_requirements": {"continuous_current": ">= 25 A"},
                    "mechanical_requirements": {"max_weight": "550 g"},
                    "software_requirements": [],
                    "dependencies": [],
                    "datasheet_url": None,
                    "alternatives": [],
                    "selection_reason": "Specific battery vendor selection deferred to procurement phase.",
                    "confidence": 0.88,
                    "source_evidence_ids": [],
                    "validation_required": True,
                },
            ],
            "component_requirements": [
                {
                    "requirement_id": "COMP-REQ-001",
                    "category": "SBC",
                    "quantity": 1,
                    "required_specifications": {"ai_compute": ">= 40 TOPS", "memory": "8 GB", "voltage": "5.0 V"},
                    "source_subsystem": "SUB-001",
                    "reason": "Host for real-time YOLOv8 neural inference.",
                    "source_decision_ids": ["DEC-001"],
                },
                {
                    "requirement_id": "COMP-REQ-002",
                    "category": "thermal camera",
                    "quantity": 1,
                    "required_specifications": {"resolution": "160x120", "spectral_range": "LWIR", "interface": "SPI"},
                    "source_subsystem": "SUB-002",
                    "reason": "Thermal imaging for human target identification.",
                    "source_decision_ids": ["DEC-001"],
                },
            ],
            "subsystems": [
                {"subsystem_id": "SUB-001", "name": "Compute Subsystem", "item_count": 1},
                {"subsystem_id": "SUB-002", "name": "Sensing Subsystem", "item_count": 1},
                {"subsystem_id": "SUB-003", "name": "Power Subsystem", "item_count": 3},
                {"subsystem_id": "SUB-004", "name": "Control Subsystem", "item_count": 1},
            ],
            "conflicts": [
                {
                    "conflict_id": "CONFLICT-001",
                    "type": "interface_resource",
                    "description": "FLIR Lepton and Barometer share the primary I2C bus; ensure distinct 7-bit slave addresses (FLIR: 0x2A, BMP280: 0x76).",
                    "affected_components": ["FLIR Lepton 3.5", "BMP280 Barometer"],
                    "severity": "low",
                    "resolution": "Confirmed distinct addresses; no bus multiplexer required.",
                    "validation_required": True,
                }
            ],
            "compatibility_checks": [
                {
                    "check_id": "COMPAT-001",
                    "type": "electrical",
                    "status": "passed",
                    "description": "FLIR Lepton (3.3V logic) and Jetson Orin Nano (3.3V GPIO/SPI header) logic levels are directly compatible.",
                    "affected_items": ["BOM-001", "BOM-002"],
                    "required_action": None,
                },
                {
                    "check_id": "COMPAT-002",
                    "type": "power",
                    "status": "passed",
                    "description": "TPS565208 5A regulator delivers sufficient current headroom for Jetson 15W peak mode (3.0A).",
                    "affected_items": ["BOM-001", "BOM-004"],
                    "required_action": "Verify regulator thermal dissipation under full 5A load.",
                },
            ],
            "alternatives": [
                {
                    "alternative_id": "ALT-001",
                    "part_number": "SC1111",
                    "manufacturer": "Raspberry Pi",
                    "compatibility": "architecture_alternative",
                    "differences": ["Lower AI performance (~0.5 TOPS vs 40 TOPS)"],
                    "reason": "Alternative if neural model is run on ground station.",
                    "confidence": 0.85,
                    "datasheet_url": "https://datasheets.raspberrypi.com/rpi5/raspberry-pi-5-product-brief.pdf",
                }
            ],
            "validation_requirements": [
                {
                    "validation_id": "VAL-BOM-001",
                    "type": "electrical",
                    "description": "Verify 5.0V bus ripple under simultaneous 15W Jetson Orin burst and radio transmission.",
                    "affected_items": ["BOM-001", "BOM-004", "BOM-005"],
                    "severity": "high",
                    "status": "required",
                    "reason": "Prevent GPU brownout reset during target acquisition bursts.",
                }
            ],
            "unknowns": [
                {
                    "unknown_id": "UNKNOWN-001",
                    "description": "Exact internal resistance of 4S LiPo under 0 deg C cold-weather discharge.",
                    "affected_items": ["BOM-006"],
                    "why_it_matters": "Determines winter flight duration and voltage cut-off safety thresholds.",
                    "required_information": "Manufacturer cold-temperature discharge curves.",
                    "blocking": False,
                }
            ],
            "assumptions": [
                {
                    "assumption_id": "ASSUMP-001",
                    "description": "Carrier board logic levels for Jetson Orin Nano are standard 3.3V CMOS.",
                    "affected_items": ["BOM-001", "BOM-002", "BOM-003"],
                    "confidence": 0.98,
                    "validation_required": True,
                }
            ],
            "traceability": [
                {
                    "traceability_id": "TRACE-BOM-001",
                    "requirement_ids": ["REQ-001"],
                    "subsystem_ids": ["SUB-001"],
                    "component_requirement_ids": ["COMP-REQ-001"],
                    "bom_item_ids": ["BOM-001"],
                    "validation_ids": ["VAL-BOM-001"],
                }
            ],
        }

        return schema.model_validate(data)
