'use client';

import React, { useState, useEffect } from 'react';
import {
  Calendar,
  X,
  Check,
  Loader2,
  ExternalLink,
  AlertTriangle,
  Download,
  Copy,
  CheckCircle2,
  Clock,
  ArrowUpRight
} from 'lucide-react';
import { API_BASE_URL } from '@/lib/api';

interface GanttTask {
  id: string;
  name: string;
  start?: string;
  end?: string;
  progress?: number;
  dependencies?: string;
  deliverable?: string;
}

interface GoogleCalendarExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  projectId?: string | number;
  projectName?: string;
  ganttTasks: GanttTask[];
  apiBase?: string;
}

interface GeneratedLink {
  id: string;
  name: string;
  start?: string;
  end?: string;
  url: string;
}

/**
 * Format date string (YYYY-MM-DD or ISO) into Google Calendar YYYYMMDD format.
 * End date is exclusive for all-day events.
 */
function toGoogleDateRange(startStr?: string, endStr?: string): string {
  try {
    const today = new Date();
    const cleanStart = startStr ? startStr.split('T')[0] : today.toISOString().split('T')[0];
    const sParts = cleanStart.split('-').map(Number);
    const startDate = new Date(sParts[0], sParts[1] - 1, sParts[2]);

    let endDate: Date;
    if (endStr) {
      const cleanEnd = endStr.split('T')[0];
      const eParts = cleanEnd.split('-').map(Number);
      endDate = new Date(eParts[0], eParts[1] - 1, eParts[2] + 1); // Google Calendar end date is exclusive
    } else {
      endDate = new Date(sParts[0], sParts[1] - 1, sParts[2] + 1);
    }

    const fmt = (d: Date) => {
      const y = d.getFullYear();
      const m = String(d.getMonth() + 1).padStart(2, '0');
      const day = String(d.getDate()).padStart(2, '0');
      return `${y}${m}${day}`;
    };

    return `${fmt(startDate)}/${fmt(endDate)}`;
  } catch {
    const d = new Date();
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${y}${m}${day}/${y}${m}${String(d.getDate() + 1).padStart(2, '0')}`;
  }
}

/**
 * Builds direct Google Calendar URL client-side.
 */
function buildClientGoogleCalendarUrl(
  task: GanttTask,
  projectName: string,
  projectId: string | number,
  timezone: string
): string {
  const taskName = task.name || 'Engineering Task';
  const title = `${projectName} - ${taskName}`;
  const dates = toGoogleDateRange(task.start, task.end);

  const startStr = task.start || 'TBD';
  const endStr = task.end || 'TBD';
  const details = [
    `Project: ${projectName}`,
    `Task: ${taskName}`,
    `Scheduled: ${startStr} to ${endStr}`,
    `Deliverable: ${task.deliverable || 'Engineering Output'}`,
    `Dependencies: ${task.dependencies || 'None'}`,
    '',
    `Project ID: ${projectId}`,
    `Generated by Workline / ArmourIQ AI`
  ].join('\n');

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: title,
    dates: dates,
    details: details,
    location: 'Workline AI Engine',
    ctz: timezone || 'UTC'
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

/**
 * Builds RFC 5545 iCalendar content for multi-event download.
 */
function buildIcsFileContent(tasks: GanttTask[], projectName: string, projectId: string | number): string {
  const now = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';

  const formatIcsDate = (dateStr?: string, addDays: number = 0) => {
    const d = dateStr ? new Date(dateStr) : new Date();
    d.setDate(d.getDate() + addDays);
    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${y}${m}${day}`;
  };

  const events = tasks.map((task, idx) => {
    const uid = `workline-${projectId}-${task.id || idx}-${Date.now()}@armouriq.local`;
    const dtstart = formatIcsDate(task.start, 0);
    const dtend = formatIcsDate(task.end || task.start, 1);
    const summary = `${projectName} - ${task.name}`;
    const desc = `Project: ${projectName}\\nTask: ${task.name}\\nDeliverable: ${task.deliverable || 'None'}\\nDependencies: ${task.dependencies || 'None'}`;

    return [
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${now}`,
      `DTSTART;VALUE=DATE:${dtstart}`,
      `DTEND;VALUE=DATE:${dtend}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:${desc}`,
      'LOCATION:Workline AI Engine',
      'STATUS:CONFIRMED',
      'END:VEVENT'
    ].join('\r\n');
  }).join('\r\n');

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Workline AI//Engineering Execution Timeline//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    events,
    'END:VCALENDAR'
  ].join('\r\n');
}

export default function GoogleCalendarExportModal({
  isOpen,
  onClose,
  projectId = 'default',
  projectName = 'Engineering Project',
  ganttTasks = [],
  apiBase = API_BASE_URL
}: GoogleCalendarExportModalProps) {
  const [selectedTaskIds, setSelectedTaskIds] = useState<string[]>([]);
  const [selectAll, setSelectAll] = useState(true);
  const [timezone, setTimezone] = useState('UTC');
  const [loading, setLoading] = useState(false);
  const [generatedLinks, setGeneratedLinks] = useState<GeneratedLink[]>([]);
  const [copiedLink, setCopiedLink] = useState<string | null>(null);

  // Auto-detect browser timezone
  useEffect(() => {
    if (isOpen && typeof window !== 'undefined') {
      try {
        const detectedTz = Intl.DateTimeFormat().resolvedOptions().timeZone;
        if (detectedTz) {
          setTimezone(detectedTz);
        }
      } catch (e) {
        console.error('Failed to detect timezone:', e);
      }
    }
  }, [isOpen]);

  // Pre-select all tasks initially
  useEffect(() => {
    if (isOpen && ganttTasks.length > 0) {
      const allIds = ganttTasks.map((t) => t.id || t.name).filter(Boolean);
      setSelectedTaskIds(allIds);
      setSelectAll(true);
      setGeneratedLinks([]);
    }
  }, [isOpen, ganttTasks]);

  if (!isOpen) return null;

  const hasNoTasks = !ganttTasks || ganttTasks.length === 0;
  const isExportDisabled = hasNoTasks;

  const handleSelectAllToggle = () => {
    if (selectAll) {
      setSelectedTaskIds([]);
      setSelectAll(false);
    } else {
      const allIds = ganttTasks.map((t) => t.id || t.name).filter(Boolean);
      setSelectedTaskIds(allIds);
      setSelectAll(true);
    }
  };

  const handleTaskToggle = (taskId: string) => {
    if (selectedTaskIds.includes(taskId)) {
      const updated = selectedTaskIds.filter((id) => id !== taskId);
      setSelectedTaskIds(updated);
      setSelectAll(updated.length === ganttTasks.length);
    } else {
      const updated = [...selectedTaskIds, taskId];
      setSelectedTaskIds(updated);
      setSelectAll(updated.length === ganttTasks.length);
    }
  };

  const selectedTasks = ganttTasks.filter((t) =>
    selectedTaskIds.includes(t.id || t.name)
  );

  // Instant 1-Click .ics Download
  const handleDownloadIcs = () => {
    if (selectedTasks.length === 0) return;
    const icsContent = buildIcsFileContent(selectedTasks, projectName, projectId);
    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
    link.download = `${safeName}_timeline.ics`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  // Google Calendar URL Generator & Tab Launcher
  const handleExportGoogleCalendar = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (selectedTasks.length === 0) return;

    setLoading(true);

    let links: GeneratedLink[] = [];

    // Attempt backend generation with graceful fallback to client-side
    try {
      const baseUrl = (apiBase || API_BASE_URL || '').replace(/\/$/, '');
      const res = await fetch(`${baseUrl}/api/calendar/generate-links`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          project_id: projectId,
          project_name: projectName,
          task_ids: selectedTaskIds,
          tasks: selectedTasks,
          timezone: timezone
        })
      });

      if (res.ok) {
        const backendLinks = await res.json();
        if (Array.isArray(backendLinks) && backendLinks.length > 0) {
          links = backendLinks.map((item: any, idx: number) => ({
            id: item.task_id || selectedTasks[idx]?.id || String(idx),
            name: item.task_name || selectedTasks[idx]?.name || `Task ${idx + 1}`,
            start: item.start || selectedTasks[idx]?.start,
            end: item.end || selectedTasks[idx]?.end,
            url: item.google_calendar_link
          }));
        }
      }
    } catch (err) {
      console.warn('Backend calendar generation fallback to local URL synthesis:', err);
    }

    // Fallback if backend failed or returned empty
    if (links.length === 0) {
      links = selectedTasks.map((task) => ({
        id: task.id || task.name,
        name: task.name,
        start: task.start,
        end: task.end,
        url: buildClientGoogleCalendarUrl(task, projectName, projectId, timezone)
      }));
    }

    setGeneratedLinks(links);
    setLoading(false);

    // Open first tab immediately
    if (links.length === 1) {
      window.open(links[0].url, '_blank');
      onClose();
    } else if (links.length > 1) {
      // Open the first event tab, and keep the modal open with the remaining links ready to click or download
      window.open(links[0].url, '_blank');
    }
  };

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedLink(id);
    setTimeout(() => setCopiedLink(null), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-xs p-4">
      <div className="glass-panel border border-cyan-500/30 bg-zinc-950 max-w-xl w-full rounded-2xl relative p-6 space-y-5 shadow-2xl shadow-cyan-950/40 animate-fade-in font-mono text-xs text-slate-300">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between border-b border-zinc-850 pb-3.5">
          <div className="flex items-center gap-2.5 text-cyan-400">
            <div className="p-1.5 rounded-lg bg-cyan-950/60 border border-cyan-700/40">
              <Calendar className="w-4 h-4 text-cyan-400" />
            </div>
            <div>
              <h3 className="text-xs font-bold uppercase tracking-widest text-slate-100">
                Export Execution Timeline
              </h3>
              <p className="text-[10px] text-slate-400 font-normal">
                {projectName} • {selectedTasks.length} tasks selected
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-500 hover:text-slate-200 transition-colors cursor-pointer p-1 rounded-lg hover:bg-zinc-900"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Warning if no tasks */}
        {isExportDisabled ? (
          <div className="bg-amber-950/20 border border-amber-800/40 p-4 rounded-xl flex items-start gap-2.5 text-amber-400">
            <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
            <div>
              <p className="font-bold uppercase tracking-wider text-[10px]">No Tasks Available</p>
              <p className="text-[10px] leading-normal mt-1 text-slate-400">
                Execution timeline tasks have not been generated yet. Create or load a project roadmap first.
              </p>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            {/* Quick action bar */}
            <div className="grid grid-cols-2 gap-2.5">
              <button
                type="button"
                onClick={handleDownloadIcs}
                disabled={selectedTaskIds.length === 0}
                className="flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-xl border border-emerald-500/30 bg-emerald-950/30 hover:bg-emerald-900/40 text-emerald-300 font-bold text-[11px] transition-all cursor-pointer disabled:opacity-40"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .ics File</span>
              </button>

              <button
                type="button"
                onClick={() => handleExportGoogleCalendar()}
                disabled={loading || selectedTaskIds.length === 0}
                className="flex items-center justify-center gap-2 px-3.5 py-2.5 rounded-xl border border-cyan-500/40 bg-cyan-600 hover:bg-cyan-500 text-white font-bold text-[11px] transition-all cursor-pointer disabled:opacity-40 shadow-lg shadow-cyan-950/50"
              >
                {loading ? (
                  <>
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    <span>Preparing...</span>
                  </>
                ) : (
                  <>
                    <ExternalLink className="w-3.5 h-3.5" />
                    <span>Open in Google Calendar</span>
                  </>
                )}
              </button>
            </div>

            {/* If Links Generated: Show Interactive Link Directory */}
            {generatedLinks.length > 0 && (
              <div className="bg-cyan-950/20 border border-cyan-500/30 rounded-xl p-3.5 space-y-2.5">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5 text-cyan-400 text-[10px] font-bold uppercase">
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Calendar Links Ready ({generatedLinks.length})</span>
                  </div>
                  <span className="text-[9px] text-slate-400">
                    Click any task below to open directly
                  </span>
                </div>

                <div className="max-h-[140px] overflow-y-auto space-y-1.5 pr-1">
                  {generatedLinks.map((item) => (
                    <div
                      key={item.id}
                      className="flex items-center justify-between gap-2 p-2 rounded-lg bg-zinc-900/80 border border-zinc-800 hover:border-cyan-500/50 transition-all text-[10px]"
                    >
                      <div className="truncate flex-1">
                        <span className="font-bold text-slate-200 block truncate">{item.name}</span>
                        {item.start && (
                          <span className="text-[9px] text-slate-500 block">
                            {item.start} → {item.end || 'Finish'}
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-1.5 shrink-0">
                        <button
                          type="button"
                          onClick={() => copyToClipboard(item.url, item.id)}
                          className="p-1 rounded bg-zinc-800 hover:bg-zinc-700 text-slate-300 transition-colors"
                          title="Copy Google Calendar URL"
                        >
                          {copiedLink === item.id ? (
                            <Check className="w-3 h-3 text-emerald-400" />
                          ) : (
                            <Copy className="w-3 h-3" />
                          )}
                        </button>
                        <a
                          href={item.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center gap-1 px-2 py-1 rounded bg-cyan-600/80 hover:bg-cyan-500 text-white font-bold text-[9px] transition-colors"
                        >
                          <span>Open</span>
                          <ArrowUpRight className="w-2.5 h-2.5" />
                        </a>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Task Checklist Selector */}
            <div className="space-y-2">
              <div className="flex items-center justify-between border-b border-zinc-850 pb-1.5">
                <label className="text-[10px] text-slate-400 uppercase font-bold tracking-wider">
                  Select Tasks to Export ({selectedTaskIds.length}/{ganttTasks.length})
                </label>
                <label className="flex items-center gap-1.5 cursor-pointer text-[10px] font-bold text-cyan-400">
                  <input
                    type="checkbox"
                    checked={selectAll}
                    onChange={handleSelectAllToggle}
                    className="rounded bg-zinc-950 border-zinc-800 text-cyan-500 focus:ring-0 w-3.5 h-3.5"
                  />
                  Select All
                </label>
              </div>

              <div className="max-h-[170px] overflow-y-auto space-y-1.5 pr-1 border border-zinc-850/80 rounded-xl p-2 bg-zinc-900/30">
                {ganttTasks.map((task) => {
                  const taskId = task.id || task.name;
                  const isChecked = selectedTaskIds.includes(taskId);
                  return (
                    <label
                      key={taskId}
                      className={`flex items-start gap-2.5 p-2 rounded-lg cursor-pointer select-none transition-colors ${
                        isChecked ? 'bg-cyan-950/20 border border-cyan-700/30' : 'hover:bg-zinc-900/50 border border-transparent'
                      }`}
                    >
                      <input
                        type="checkbox"
                        checked={isChecked}
                        onChange={() => handleTaskToggle(taskId)}
                        className="rounded bg-zinc-950 border-zinc-800 text-cyan-500 focus:ring-0 w-3.5 h-3.5 mt-0.5"
                      />
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-[10px] text-slate-200 font-bold truncate">
                            {task.name}
                          </span>
                          {task.start && (
                            <span className="text-[9px] text-cyan-400/80 font-mono shrink-0 flex items-center gap-1">
                              <Clock className="w-2.5 h-2.5" />
                              {task.start}
                            </span>
                          )}
                        </div>
                        {task.deliverable && (
                          <span className="text-[9px] text-slate-400 block truncate mt-0.5">
                            Deliverable: {task.deliverable}
                          </span>
                        )}
                      </div>
                    </label>
                  );
                })}
              </div>
            </div>

            {/* Timezone Indicator */}
            <div className="flex items-center justify-between px-3 py-2 rounded-lg bg-zinc-900/50 border border-zinc-850 text-[10px] text-slate-400">
              <span className="text-slate-400">Target Timezone</span>
              <span className="font-mono text-cyan-400 font-bold">{timezone}</span>
            </div>

            {/* Footer Buttons */}
            <div className="flex items-center justify-end gap-2 pt-3 border-t border-zinc-850">
              <button
                type="button"
                onClick={onClose}
                className="bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-slate-400 hover:text-slate-200 px-4 py-2 rounded-xl cursor-pointer font-bold transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
}
