"""
Deterministic mock provider — used in tests and offline mode.
Never invents engineering values; returns clearly labelled placeholder prose.
"""
from typing import Dict
from research_agents.documentation_agent.providers.base import BaseDocProvider


class MockDocProvider(BaseDocProvider):

    def generate_section(self, section_name: str, context: Dict) -> str:
        doc_type = context.get("document_type", "UNKNOWN")
        title    = context.get("title", "Untitled")
        return (
            f"[GENERATED PROSE — {section_name}] "
            f"Document type: {doc_type}. Title: {title}. "
            f"This section was generated by the Technical Documentation Agent. "
            f"All values herein are placeholders pending authoritative data."
        )

    def summarize_changes(self, old_text: str, new_text: str) -> str:
        old_len = len(old_text.split())
        new_len = len(new_text.split())
        delta   = new_len - old_len
        sign    = "+" if delta >= 0 else ""
        return f"Content updated: {sign}{delta} words ({old_len} → {new_len})."
