-- 001_initial_graph.sql: Tables and Relations for Unified Engineering Knowledge Graph (Agent #13)

-- 1. Project & User Hierarchy
DEFINE TABLE user SCHEMAFULL;
DEFINE TABLE team SCHEMAFULL;
DEFINE TABLE project SCHEMAFULL;

-- 2. Requirements & Research
DEFINE TABLE requirement SCHEMAFULL;
DEFINE TABLE research SCHEMAFULL;
DEFINE TABLE engineering_decision SCHEMAFULL;

-- 3. Architecture & Subsystems
DEFINE TABLE architecture SCHEMAFULL;
DEFINE TABLE subsystem SCHEMAFULL;
DEFINE TABLE interface SCHEMAFULL;
DEFINE TABLE component SCHEMAFULL;

-- 4. BOM & Procurement
DEFINE TABLE bom SCHEMAFULL;
DEFINE TABLE bom_item SCHEMAFULL;
DEFINE TABLE supplier SCHEMAFULL;
DEFINE TABLE supplier_offer SCHEMAFULL;
DEFINE TABLE procurement_plan SCHEMAFULL;
DEFINE TABLE shipping_option SCHEMAFULL;

-- 5. Implementation & Execution
DEFINE TABLE implementation_plan SCHEMAFULL;
DEFINE TABLE work_package SCHEMAFULL;
DEFINE TABLE implementation_task SCHEMAFULL;
DEFINE TABLE execution SCHEMAFULL;
DEFINE TABLE project_file SCHEMAFULL;
DEFINE TABLE test SCHEMAFULL;
DEFINE TABLE test_result SCHEMAFULL;
DEFINE TABLE evidence SCHEMAFULL;

-- 6. Validation & QA
DEFINE TABLE validation SCHEMAFULL;
DEFINE TABLE engineering_failure SCHEMAFULL;
DEFINE TABLE qa_verdict SCHEMAFULL;

-- 7. Governance, Authorization & State
DEFINE TABLE agent SCHEMAFULL;
DEFINE TABLE authorization SCHEMAFULL;
DEFINE TABLE delegation SCHEMAFULL;
DEFINE TABLE execution_receipt SCHEMAFULL;
DEFINE TABLE tool SCHEMAFULL;
DEFINE TABLE operation SCHEMAFULL;
DEFINE TABLE project_state SCHEMAFULL;
DEFINE TABLE state_event SCHEMAFULL;
DEFINE TABLE audit_event SCHEMAFULL;

-- Relations
DEFINE TABLE OWNS TYPE RELATION;
DEFINE TABLE MEMBER_OF TYPE RELATION;
DEFINE TABLE HAS_PROJECT TYPE RELATION;
DEFINE TABLE HAS_REQUIREMENT TYPE RELATION;
DEFINE TABLE SUPPORTS TYPE RELATION;
DEFINE TABLE INFORMS TYPE RELATION;
DEFINE TABLE DRIVES TYPE RELATION;
DEFINE TABLE DEFINES TYPE RELATION;
DEFINE TABLE SELECTS TYPE RELATION;
DEFINE TABLE CONTAINS TYPE RELATION;
DEFINE TABLE DEPENDS_ON TYPE RELATION;
DEFINE TABLE USES_INTERFACE TYPE RELATION;
DEFINE TABLE IMPLEMENTS_INTERFACE TYPE RELATION;
DEFINE TABLE USES TYPE RELATION;
DEFINE TABLE REQUIRES TYPE RELATION;
DEFINE TABLE INCLUDES TYPE RELATION;
DEFINE TABLE HAS_BOM TYPE RELATION;
DEFINE TABLE USES_COMPONENT TYPE RELATION;
DEFINE TABLE OFFERS TYPE RELATION;
DEFINE TABLE FOR_COMPONENT TYPE RELATION;
DEFINE TABLE FULFILLS TYPE RELATION;
DEFINE TABLE HAS_SHIPPING_OPTION TYPE RELATION;
DEFINE TABLE IMPLEMENTS TYPE RELATION;
DEFINE TABLE EXECUTED_AS TYPE RELATION;
DEFINE TABLE MODIFIED TYPE RELATION;
DEFINE TABLE VERIFIED_BY TYPE RELATION;
DEFINE TABLE HAS_RESULT TYPE RELATION;
DEFINE TABLE PROVES TYPE RELATION;
DEFINE TABLE VALIDATES TYPE RELATION;
DEFINE TABLE CHECKS TYPE RELATION;
DEFINE TABLE IDENTIFIES TYPE RELATION;
DEFINE TABLE AFFECTS TYPE RELATION;
DEFINE TABLE SUPERSEDES TYPE RELATION;
DEFINE TABLE AUTHORIZES TYPE RELATION;
DEFINE TABLE DELEGATES_TO TYPE RELATION;
DEFINE TABLE HAS_RECEIPT TYPE RELATION;
DEFINE TABLE USED_TOOL TYPE RELATION;
DEFINE TABLE PERFORMED_OPERATION TYPE RELATION;
DEFINE TABLE HAS_STATE_EVENT TYPE RELATION;
