/**
 * Engineering Knowledge Graph entity types and statuses.
 */

export enum EntityType {
  PROJECT = "PROJECT",
  TEAM = "TEAM",
  DOCUMENT = "DOCUMENT",
  SECTION = "SECTION",
  COMPONENT = "COMPONENT",
  PART_NUMBER = "PART_NUMBER",
  MANUFACTURER = "MANUFACTURER",
  DATASHEET = "DATASHEET",
  SPECIFICATION = "SPECIFICATION",
  REQUIREMENT = "REQUIREMENT",
  DECISION = "DECISION",
  BOM_ITEM = "BOM_ITEM",
  PROCUREMENT_ITEM = "PROCUREMENT_ITEM",
  PROTOCOL = "PROTOCOL",
  INTERFACE = "INTERFACE",
  SENSOR = "SENSOR",
  ACTUATOR = "ACTUATOR",
  MATERIAL = "MATERIAL",
  TOOL = "TOOL",
  SOFTWARE = "SOFTWARE",
  DATASET = "DATASET",
  MODEL = "MODEL",
  ALGORITHM = "ALGORITHM",
  STANDARD = "STANDARD",
  RESEARCH_CONCEPT = "RESEARCH_CONCEPT",
}

export enum EntityStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUPERSEDED = "SUPERSEDED",
  UNRESOLVED = "UNRESOLVED",
  CONFLICTED = "CONFLICTED",
  DEPRECATED = "DEPRECATED",
}
