from typing import Dict, List

# Static map of allowed scopes (tools) per agent name
AGENT_SCOPES: Dict[str, List[str]] = {
    "Planner Agent": ["delegate", "generate_dependency_graph", "ask_connection_assistant"],
    "Retrieval Agent": ["search_projects", "fetch_sources"],
    "Extraction Agent": ["extract_components", "fetch_datasheets", "extraction.media"],
    "Cost Engine": ["calculate_total_cost"],
    "Alternative Finder": ["find_alternatives"],
    "Voltage Checker": ["check_voltage_compatibility", "calculate_power_budget"],
    "Pin Generator": ["generate_pin_map", "generate_wiring_diagram"],
    "BOM Export Engine": ["export_bom"],
    "ProcurementAgent": ["generate_optimized_bom", "calculate_landed_cost", "find_alternative_components"],
    "Research Agent": ["search_papers", "summarize_papers", "rank_papers"],
    "Validation Agent": ["validate_architecture"],
    "Optimization Agent": ["optimize_components"],
    "Planning Agent": ["generate_roadmap", "generate_gantt"],
    "Export Agent": ["export_pdf", "export_csv", "export_markdown", "export_docx", "export.media"],
    "CollaborationAgent": ["invite_member", "assign_role", "comment"],
    "VersionAgent": ["save_version", "rollback_version", "fork_project"],
    "ThermalAgent": ["analyze_thermal_risk"],
    "ContradictionAgent": ["detect_contradictions"],
    "KnowledgeGraphAgent": ["graph.read", "graph.insert", "graph.update"],
    "CalendarAgent": ["calendar.export", "calendar.update", "calendar.download"],
    "CalendarExportAgent": ["calendar.export", "calendar.generate_link"],
    "EngineeringExecutionAgent": [
        "filesystem",
        "filesystem.read",
        "filesystem.write",
        "filesystem.create",
        "filesystem.modify",
        "filesystem.delete",
        "shell",
        "git",
        "python",
        "compiler",
        "test_runner",
        "build_system",
        "simulation",
        "container",
        "delegate",
    ],
    "VerificationQAAgent": [
        "test_runner",
        "pytest",
        "static_analysis",
        "file_inspection",
        "security_scan",
        "filesystem.read",
        "shell",
    ],
    "EngineeringKnowledgeGraphAgent": [
        "graph.read",
        "graph.insert",
        "graph.update",
        "graph.query",
        "graph.trace",
        "graph.impact",
        "graph.export",
        "graph.state",
    ],
    "ProjectLifecycleOrchestrator": [
        "orchestration.observe",
        "orchestration.evaluate",
        "orchestration.decide",
        "orchestration.delegate",
        "orchestration.revalidate",
        "orchestration.human",
        "orchestration.state",
        "delegate",
    ],
    "EngineeringCopilotAgent": [
        "copilot.read",
        "copilot.query",
        "copilot.trace",
        "copilot.explain",
        "copilot.propose",
        "graph.read",
    ],
    "EngineeringChangeControlAgent": [
        "change.create",
        "change.analyze",
        "change.version",
        "change.propagate",
        "change.approve",
        "change.revalidate",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "EngineeringComplianceAgent": [
        "compliance.evaluate",
        "compliance.rules",
        "compliance.gate",
        "compliance.matrix",
        "compliance.waiver",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "EngineeringVerificationAgent": [
        "verification.plan",
        "verification.test",
        "verification.execute",
        "verification.evidence",
        "verification.reverify",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "EngineeringSimulationAgent": [
        "simulation.model",
        "simulation.twin",
        "simulation.execute",
        "simulation.scenario",
        "simulation.sweep",
        "simulation.evidence",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
}
