from typing import Dict, List

# Static map of allowed scopes (tools) per agent name
AGENT_SCOPES: Dict[str, List[str]] = {
    "Planner Agent": ["delegate", "generate_dependency_graph", "ask_connection_assistant", "analyze_engineering_idea", "populate_knowledge_graph"],
    "Retrieval Agent": ["search_projects", "fetch_sources", "nexar_mcp_search", "nexar_mcp_lookup_mpn", "nexar_mcp_get_datasheet", "research_components", "recommend_components", "retrieve_datasheet"],
    "Extraction Agent": ["extract_components", "fetch_datasheets", "extraction.media", "retrieve_datasheet"],
    "Cost Engine": ["calculate_total_cost"],
    "Alternative Finder": ["find_alternatives"],
    "Voltage Checker": ["check_voltage_compatibility", "calculate_power_budget"],
    "Pin Generator": ["generate_pin_map", "generate_wiring_diagram"],
    "BOM Export Engine": ["export_bom"],
    "ProcurementAgent": ["generate_optimized_bom", "calculate_landed_cost", "find_alternative_components", "nexar_mcp_search", "nexar_mcp_lookup_mpn", "nexar_mcp_get_datasheet", "research_components"],
    "Research Agent": ["search_papers", "summarize_papers", "rank_papers", "search_scholarly_papers", "retrieve_datasheet"],
    "Validation Agent": ["validate_architecture"],
    "Optimization Agent": ["optimize_components"],
    "Planning Agent": ["generate_roadmap", "generate_gantt"],
    "Export Agent": ["export_pdf", "export_csv", "export_markdown", "export_docx", "export.media"],
    "CollaborationAgent": ["invite_member", "assign_role", "comment"],
    "VersionAgent": ["save_version", "rollback_version", "fork_project"],
    "ThermalAgent": ["analyze_thermal_risk"],
    "ContradictionAgent": ["detect_contradictions"],
    "KnowledgeGraphAgent": ["graph.read", "graph.insert", "graph.update", "populate_knowledge_graph"],
    "CalendarAgent": ["calendar.export", "calendar.update", "calendar.download"],
    "CalendarExportAgent": ["calendar.export", "calendar.generate_link"],
    "EngineeringExecutionAgent": [
        "filesystem",
        "filesystem.read",
        "filesystem.write",
        "filesystem.create",
        "filesystem.modify",
        "filesystem.delete",
        "shell",
        "git",
        "python",
        "compiler",
        "test_runner",
        "build_system",
        "simulation",
        "container",
        "delegate",
    ],
    "VerificationQAAgent": [
        "test_runner",
        "pytest",
        "static_analysis",
        "file_inspection",
        "security_scan",
        "filesystem.read",
        "shell",
    ],
    "EngineeringKnowledgeGraphAgent": [
        "graph.read",
        "graph.insert",
        "graph.update",
        "graph.query",
        "graph.trace",
        "graph.impact",
        "graph.export",
        "graph.state",
    ],
    "ProjectLifecycleOrchestrator": [
        "orchestration.observe",
        "orchestration.evaluate",
        "orchestration.decide",
        "orchestration.delegate",
        "orchestration.revalidate",
        "orchestration.human",
        "orchestration.state",
        "delegate",
    ],
    "EngineeringCopilotAgent": [
        "copilot.read",
        "copilot.query",
        "copilot.trace",
        "copilot.explain",
        "copilot.propose",
        "graph.read",
        "nexar_mcp_search",
        "nexar_mcp_lookup_mpn",
        "nexar_mcp_get_datasheet",
    ],
    "EngineeringChangeControlAgent": [
        "change.create",
        "change.analyze",
        "change.version",
        "change.propagate",
        "change.approve",
        "change.revalidate",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "EngineeringComplianceAgent": [
        "compliance.evaluate",
        "compliance.rules",
        "compliance.gate",
        "compliance.matrix",
        "compliance.waiver",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "EngineeringVerificationAgent": [
        "verification.plan",
        "verification.test",
        "verification.execute",
        "verification.evidence",
        "verification.reverify",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "EngineeringSimulationAgent": [
        "simulation.model",
        "simulation.twin",
        "simulation.execute",
        "simulation.scenario",
        "simulation.sweep",
        "simulation.evidence",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "EngineeringOptimizationAgent": [
        "optimization.create",
        "optimization.evaluate",
        "optimization.pareto",
        "optimization.tradeoff",
        "optimization.select",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "EngineeringRiskAgent": [
        "risk.identify",
        "risk.fmea",
        "risk.propagation",
        "risk.mitigate",
        "risk.reassess",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "SecurityThreatModelingAgent": [
        "security.assets",
        "security.surface",
        "security.threats",
        "security.attack_path",
        "security.controls",
        "security.mitigate",
        "security.reassess",
        "security.tests",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "ManufacturingDFMAgent": [
        "mfg.dfm",
        "mfg.dfa",
        "mfg.process",
        "mfg.tolerance",
        "mfg.variation",
        "mfg.tooling",
        "mfg.sequence",
        "mfg.inspection",
        "mfg.readiness",
        "mfg.recommend",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "CostSupplyChainAgent": [
        "cost.estimate",
        "cost.bom",
        "cost.drivers",
        "cost.suppliers",
        "cost.risk",
        "cost.make_buy",
        "cost.impact",
        "cost.dashboard",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "DeploymentOpsAgent": [
        "ops.deployment",
        "ops.readiness",
        "ops.commissioning",
        "ops.config",
        "ops.environment",
        "ops.monitoring",
        "ops.incident",
        "ops.recovery",
        "ops.maintenance",
        "ops.spares",
        "ops.decommission",
        "graph.read",
        "graph.insert",
        "graph.update",
    ],
    "TechDocAgent": [
        "techdoc:create", "techdoc:read", "techdoc:review",
        "techdoc:approve", "techdoc:publish", "techdoc:publish:controlled",
        "techdoc:trace", "techdoc:conflict", "techdoc:export",
        "techdoc:quality", "techdoc:compare", "techdoc:withdraw",
        "techdoc:archive", "techdoc:template",
    ],
}
